//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTruong.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Admin
    {
        public int ID { get; set; }

        [DisplayName("Tên ng??i dùng")]
        [Required(ErrorMessage ="Vui lòng nh?p tên")]
        [StringLength(100,ErrorMessage ="Tên không nh?p quá 100 ký t?")]
        public string NameUser { get; set; }
        public string RoleUser { get; set; }
        public string PasswordUser { get; set; }
        
        [NotMapped]
        [Compare("PasswordUser",ErrorMessage ="Password không trung kh?p")]
        public string ConfirmPass { get; set; }

    }
}
