//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTruong.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnrollmentDetail
    {
        public int ID { get; set; }
        public Nullable<int> SubjectID { get; set; }
        public Nullable<int> EnrollID { get; set; }
        public string Status { get; set; }
    
        public virtual Enrollment Enrollment { get; set; }
        public virtual Subject Subject { get; set; }
    }
}
