//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTruong.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enrollment
    {
        public Enrollment()
        {
            this.EnrollmentDetails = new HashSet<EnrollmentDetail>();
        }
    
        public int EnrollID { get; set; }
        public Nullable<System.DateTime> EnrollDate { get; set; }
        public Nullable<int> StudentID { get; set; }
        public string Notes { get; set; }
    
        public virtual ICollection<EnrollmentDetail> EnrollmentDetails { get; set; }
        public virtual Student Student { get; set; }
    }
}
