//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTruong.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Subject
    {
        public Subject()
        {
            this.EnrollmentDetails = new HashSet<EnrollmentDetail>();
        }
        [DisplayName("Mã môn hoc")]
        public int SubjectID { get; set; }
        [DisplayName("Tên môn hoc")]
        public string SubjectName { get; set; }
        [DisplayName("Mã b? môn/khoa")]

        public string DeptCode { get; set; }
        [DisplayName("So tín ch?")]

        public Nullable<int> Credits { get; set; }
        [DisplayName("Ngày băt dau")]
        public Nullable<System.DateTime> StartDate { get; set; }
        [DisplayName("Lich hoc")]
        public string ClassTime { get; set; }
        [DisplayName("So luong sinh viên")]
        public Nullable<int> Capacity { get; set; }

        [DisplayName("Lich hoc")]
        public string Classroom { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual ICollection<EnrollmentDetail> EnrollmentDetails { get; set; }
    }
}
